#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-Camellia
version:      1.0.1
version_from: Camellia.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
